<?php


include 'utilityFucntions.php';

function program_menu() {
	$items['faculty'] = array(
	  'title' => 'Faculty',
	  'page callback' => 'faculty_search',
	  'access arguments' => array('access content'),
	);

	return $items;
}

function faculty_search() {
  $program_module_path = drupal_get_path('module', 'faculty');

  loadjs(array(
      '/javascript/libs/listjs/dist/list.js',
      '/js/libs/listjs/list.pagination.js',
      '/javascript/jquery.multiple-select.js',
      '/javascript/cookies.js',
      '/javascript/newProgram.js',
      '/javascript/clearCountries.js'
  ));

  loadcss(array(
    '/program.css',
    '/multiple-select.css'
  ));

  function getTerm($node, $f, $n = 0){
    $term =($node->{$f});
    if(!empty($term)){
      if(!empty($node->{$f}['und'][$n]['tid'])){
        $term =($node->{$f}['und'][$n]['tid']);
        settype($term, "integer");
        $term = taxonomy_term_load($term)->name;
      }
    }else{
      $term = null;
    }
    return $term;
  }

  function getTerms($node, $f){
    $term = ($node->{$f});
    if(!empty($term)){
      $terms = array();
      foreach ($term['und'] as $key => $value) {
        $terms[$key] = getTerm($node, $f, $key);
      }

      return implode(', ', $terms);
    }
  }

  function getFacultyField($node, $f){
    $term = ($node->{$f});
    if(!empty($term)){
        return $term['und'][0]['value']; 
    }
  }


  $nids = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->fields('n', array('type'))
    ->condition('n.type', 'faculty_profile')
    ->execute()
    ->fetchCol(); // returns an indexed array
  $numberofPrograms = count($nids);

  $myearList = array();
  $uyearList = array();
  $dyearList = array();

  $minstList = array();
  $uinstList = array();
  $dinstList = array();

  $mafieldList = array(); 
  $uafieldList = array(); 
  $dafieldList = array(); 

  $programCards = "";

  $x=0;
  foreach ($nids as $value) {
    $x = $x+1;

    $node = node_load($value, false);

    $name = $node->title;

    $dyear = getFacultyField($node, "field_doctorate_year");
    array_push($dyearList, $dyear);
    $uyear = getFacultyField($node, "field_undergraduate_year");
    array_push($uyearList, $uyear);
    $myear = getFacultyField($node, "field_masters_year");
    array_push($myearList, $myear);

    $minst = getFacultyField($node, "field_master_granting_inst");
    array_push($minstList, $minst);
    $uinst = getFacultyField($node, "field_undergraduate_institution");
    array_push($uinstList, $uinst);
    $dinst = getFacultyField($node, "field_doctorate_granting_institu");
    array_push($dinstList, $dinst);

    $dafield = getTerms($node, "field_doctorate_academic_field");
    array_push($dafieldList, $dafield);
    $uafield = getTerms($node, "field_undergraduate_field");
    array_push($uafieldList, $uafield);
    $mafield = getTerms($node, "field_master_academic_field");
    array_push($mafieldList, $mafield);


    $bio = getFacultyField($node, "field_short_bio");
    $link = drupal_get_path_alias("node/{$value}");
    $fcountry = getTerms($node, "field_country");

    $title = getTerms($node, "field_title");
    $website = getFacultyField($node, "field_website");
    $email = getFacultyField($node, "field_email");

    $card = '
      <tr>
        <td class="name">
          <h5>
            <a href="'.$link.'" >
            '.$name.'
            </a>
          </h5>
        </td>
        <td class="title">
          <h5 >'.$title.'</h5>
        <td class="email">
          <h5>
            <a href="mailto:'.$email.'" >
            '.$email.'
            </a>
          </h5>
        </td>
        <td class="website">
          <h5>
            <a href="http://'.$website.'" target="_blank" >
            '.$website.'
            </a>
          </h5>
        </td>
        </td>
        <td class="country">
          <h5 >'.$fcountry.'</h5>
        </td>
        <td class="bio" style="display:none">
          <h5 >'.$bio.'</h5>
        </td>
        <td style="display:none">
          <h5 class="myear">'.$myear.'</h5>
        </td>
        <td style="display:none">
          <h5 class="uyear">'.$uyear.'</h5>
        </td>
        <td style="display:none">
          <h5 class="dyear">'.$dyear.'</h5>
        </td>
        <td style="display:none">
          <h5 class="minst">'.$minst.'</h5>
        </td>
        <td style="display:none">
          <h5 class="uinst">'.$uinst.'</h5>
        </td>
        <td style="display:none">
          <h5 class="dinst">'.$dinst.'</h5>
        </td>
        <td style="display:none">
          <h5 class="mafield">'.$mafield.'</h5>
        </td>
        <td style="display:none">
          <h5 class="uafield">'.$uafield.'</h5>
        </td>
        <td style="display:none">
          <h5 class="dafield">'.$dafield.'</h5>
        </td>
      </td>
    ';
    $programCards .= $card;  
  }

  function generateOptionHTML($group){
    $optionHTML="";
    foreach (array_unique($group) as $d) {
      if($d != ""){
        $optionHTML .= "<option value='" . $d ."'>$d</option>";
      }
    }
    return $optionHTML;
  }

  return array('#markup' => '
    <div id="programList">
      <div id="controls">
        <input class="search" placeholder="Search" value=""/>
        <div id="catagories">
          <select class="dyear_s" multiple data-placeholder="<span>Choose a</span> doctorate year">'. generateOptionHTML($dyearList) . '</select>
          <select class="dinst_s" multiple data-placeholder="<span>Choose a</span> doctorate institution">'. generateOptionHTML($dinstList) . '</select>
          <select class="dafield_s" multiple data-placeholder="<span>Choose a</span> doctorate field">'. generateOptionHTML($dafieldList) . '</select>

          <select class="myear_s" multiple data-placeholder="<span>Choose a</span> masters year">'. generateOptionHTML($myearList) . '</select>
          <select class="minst_s" multiple data-placeholder="<span>Choose a</span> masters institution">'. generateOptionHTML($minstList) . '</select>
          <select class="mafield_s" multiple data-placeholder="<span>Choose a</span> masters field">'. generateOptionHTML($mafieldList) . '</select>

          <select class="uyear_s" multiple data-placeholder="<span>Choose a</span> under graduate year">'. generateOptionHTML($uyearList) . '</select>         
          <select class="uinst_s" multiple data-placeholder="<span>Choose a</span> under graduate institution">'. generateOptionHTML($uinstList) . '</select>
          <select class="uafield_s" multiple data-placeholder="<span>Choose a</span> under graduate field">'. generateOptionHTML($uafieldList) . '</select>
          
        </div>
      </div>
      <table>
        <thead>
          <tr>
            <td>
              <button class="sort" data-sort="name">name</button>
            </td>
            <td>
              <button class="sort" data-sort="title">title</button>
            </td>
            <td >
              <button class="sort" data-sort="email">email</button>
            </td>
            <td >
              <button class="sort" data-sort="website">website</button>
            </td>
            <td >
              <button class="sort" data-sort="country">country</button>
            </td>
          </tr>
        </thead>
        <tbody class="list">
          '. $programCards .'
        </tbody>
      </table>
    </div>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js"></script>
  ');
}

